try{
//  Error testing

    alert("Hello Everyone");
    alert(x);
    
}catch(err){
    // Error Handling

    // alert("Inside catch block");
    console.log(err);
    // console.log(err.name);
    // console.log(err.message);
}finally{
    alert("bye Everyone");
}